server:
    port: 9090
    session-timeout: 1800
    undertow: 
        io-threads: 4
        worker-threads: 20
        buffer-size: 1024
        buffers-per-region: 1024
        direct-buffers: true
    
