server:
  port: 9090

#  un
  undertow:
    accesslog:
#      是否启动日志
      enabled: true
#      日志存放目录
      dir: /log
#      日志格式
      pattern: common
#     日志文件名前缀
      prefix: access_log
#     日志文件名后缀
      suffix: .log

#每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
#是否分配的直接内存
    direct-buffers: true
#设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
#HTTP POST请求最大的大小
    max-http-post-size: 0
# 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20


